# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xian Liu
title: Aspiring Business and Data Analyst
email: xianqqliu@outlook.com
website: bluebeatlehd.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: 
github_username:  BlueBeatleHD
# stackoverflow_username: 
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: xianqqliu
# xing_username: 
# pinterest_username: 
youtube_username: 
# googleplus_username: 
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title:
  icon: fas fa-globe
  url: bluebeatlehd.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Xian, a recent graduate aspiring to excel as a Business Data Analyst. I'm passionate about unraveling insights from data to drive informed business decisions. Eager to leverage analytical skills and a keen interest in data interpretation, I aim to contribute meaningfully to the field of data analytics.
  
  I am actively exploring employment opportunities that not only immerse me in the realm of business and data analytics, but also foster my professional growth, and  continually broaden my expertise and propel my career forward.

  I am most skilled in: <mark>Data Analytics</mark> and <mark>Technology Management</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Broward College
        caption: 2019 - 2023
        sub_title: BASc Technology Management, Data Focus
        quote: >
        description: | # this will include new lines to allow paragraphs
          Here is a list of relevant courses to the data analytics field:
          - SQL Fundamentals
          - Database Management
          - Analyzing and Visualizing Data with Power BI
          - Advanced Data Visualization with Excel
          - Applied Data Reporting
          - Data Integration & Manipulation
          - Data Analytics Management
          - Data Analytics Technologies
          
          Technology and management:
          - Project Management
          - Agile Project Management
          - Operations Management
          - Web Systems and Technologies
          - Operations Management
          - Leadership and Supervision
          - Managing Cultural Diversity
          
          
         
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: No 1 Wok
        # link_text: boringcompany.com
        sub_title: Associate Manager
        caption: August 2018 - September 2023
        quote: >
          I started working at my parents resturant while I was attending school. I implemented strategies to streamline the end of month revenue calculations, contributing significantly to the accuracy and efficiency. This experience allowed me to blend my academic and practical skills, fostering a valuable and hands-on learning environment.
        description: | # this will include new lines to allow paragraphs
            - Led and managed a team of 6 staff members to maintain the smooth operation of the establishment and provided exceptional customer service.
            - Installed and administered a brand new Point of Sale (POS) system for the resturant, ensuring regular updates and maintenance.
            - Ran day-to-day operations, including handling staff hours and assigning duties, making bank deposits, and investigating/resolving complaints regarding service, and accommodations.
            - Implemented efficient supply chain management strategies, using a local database, optimizing inventory levels and ensuring timely delivery and use of goods.
            - Simplified monthly revenue calculation methods using Excel and Power BI to analyzed business growth using KPIs and prepared payroll information.
            - Monitored compliance with health and fire regulations regarding food preparation, serving, and building maintenance in lodging and dining facilities.
            
      - layout: left
        title: Freelance Tutoring
        # link_text: boringcompany.com
        sub_title: Tutor
        caption: October 2020 - May 2022
        quote: >
          Before I entered the IT field I was a chemistry student. Many of my classmates struggled in early level courses. I spent a large portion of time teaching the concepts in our group chat. I started tutoring when one student requested a one-on-one environment. Which led others to also request the service.
        description: | # this will include new lines to allow paragraph
            - Conducted one-on-one tutoring sessions using online platforms such as Zoom, ensuring personalized attention and tailored teaching methods to meet individual learning needs.
            - Tutored in classes such as statistics, trigonometry, algebra, general chemistry, and organic chemistry.
            - Assisted students in reviewing for upcoming exams and analyzing past exams to identify areas of weakness, devising targeted strategies to address knowledge gaps and improve exam scores.
            - Regularly monitored and evaluated student progress regularly, providing data-driven feedback to help students meet academic goals.




  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Aviation
      - Gaming
      - Weight lifting

      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
